name: Build Listings

env:
  websiteDirectory: Website

on: 
  workflow_dispatch:
  workflow_run:
    workflows: [Build Release]
    types:
      - completed
  release:
     types: [published, created, edited, unpublished, deleted, released]

permissions:
  contents: read
  pages: write
  id-token: write
  
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-listing:
    name: build-listing
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository.
        uses: actions/checkout@v2
      - name: Build listing
        id: build-listing
        uses: ./XProxy.BuildListing
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Pages
        uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.websiteDirectory }}
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
